FROM seges/tomcat:8.0.30-oracle-jre8
MAINTAINER gazo@seges.sk

USER root

COPY /conf/catalina.properties $CATALINA_HOME/conf/catalina.properties
COPY /bin $CATALINA_HOME/bin

RUN curl -o $CATALINA_HOME/lib/mail.jar http://central.maven.org/maven2/javax/mail/mail/1.4.1/mail-1.4.1.jar && \
    curl -o $CATALINA_HOME/lib/postgresql.jar http://central.maven.org/maven2/org/postgresql/postgresql/9.4.1207.jre7/postgresql-9.4.1207.jre7.jar && \
    curl -o $CATALINA_HOME/lib/bonecp.jar http://central.maven.org/maven2/com/jolbox/bonecp/0.7.1.RELEASE/bonecp-0.7.1.RELEASE.jar && \
    curl -o $CATALINA_HOME/lib/bonecp-provider.jar http://central.maven.org/maven2/com/jolbox/bonecp-provider/0.7.1.RELEASE/bonecp-provider-0.7.1.RELEASE.jar

ENV XWIKI_VERSION 7.4

RUN curl -o $CATALINA_HOME/webapps/xwiki.war http://download.forge.ow2.org/xwiki/xwiki-enterprise-web-${XWIKI_VERSION}.war
RUN cd $CATALINA_HOME/webapps; mkdir xwiki; cd xwiki && \
    unzip ../xwiki.war

COPY /webapps/hibernate.cfg.xml $CATALINA_HOME/webapps/xwiki/WEB-INF/hibernate.cfg.xml

RUN chown -R tomcat:tomcat $CATALINA_HOME

USER tomcat

